services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
#    image: gethomepage/homepage:v0.10.9
    container_name: homepage
    ports:
      - 80:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
    restart: always
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
#      - ./var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
