---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Proxmox VE: 
    - PVE-01:
        icon: /images/proxmox.png
        href: https://172.16.3.121:8006
        ping: 172.16.3.121
        statusStyle: 'dot'
        widget:
           type: proxmox
           url: https://172.16.3.121:8006
           username: Homepage@pam!api-readonly 
           password: cacf9beb-9849-425b-a146-c3ab908f844e 
           node: pve01