---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

#- resources:
#    cpu: true
#    memory: true
#    disk: /

#- search:
#    provider: duckduckgo
#    target: _blank
#    hideInternetSearch: false

- logo:
    icon: /images/fortinet.png
#    icon: /images/Fortinet-logo.svg

- openmeteo:
    label: Menomonee Falls, WI # optional
    latitude: 43.15218 
    longitude: -88.10153 
    timezone: America/Chicago # optional
    units: imperial #metric # or imperial
    cache: 10 # Time in minutes to cache API responses, to stay within limits

- datetime:
    text_size: xl
    format:
      dateStyle: short
      timeStyle: short
      hour12: true
