---
      - name: Mount ISO image on CD-ROM 
        community.proxmox.proxmox_disk:
          api_user: "{{ proxmox_api_user }}"
          api_token_id: "{{ proxmox_api_token_id }}"
          api_token_secret: "{{ proxmox_api_token_secret }}"
          api_host: "{{ proxmox_api_host }}"
          vmid: "{{ item.vmid }}"
          name: "{{ item.name }}"
          disk: ide2
          media: cdrom
          # iso_image: "{{ proxmox_storage_name }}:iso/{{ item.name }}_bootstrap.iso"
          iso_image: "local:iso/{{ item.name }}_bootstrap.iso"
          state: present
        register: vm_info
        loop: "{{ lookup('vars',  group_name)  }}"

      - name: Display register dynamic variable vm_info
        debug:
          msg: " {{ item.msg }}"
        loop: "{{ vm_info.results  }}"

