---
  proxmox:
    - name: pve01
  
  fortigate_sdwan:
    - name: FGT-Hub-01a 
      vmid: 110
      cores: 1
      vcpus: 1
      memory: 4096
      type: FGT
      logsize: 32
      ipconfig0: 'ip=10.198.7.2/29,gw=10.198.1.1'
      ipconfig1: 'ip=10.198.8.2/29,gw=10.198.2.1'
      ipconfig2: 'ip=10.100.88.1/24'
      ipconfig3: 'ip=10.100.55.51/24'
      ipconfig4: 'ip=10.100.77.1/24'
      vlanconfig0: COREWAN1 
      vlanconfig1: COREWAN2 
      vlanconfig2: ISFW01 
      vlanconfig3: FTNTMGT 
      vlanconfig4: DMZ01 
      vlanconfig5: HAHUB01 

    - name: FGT-Hub-01b 
      vmid: 111
      cores: 1
      vcpus: 1
      memory: 4096
      type: FGT
      logsize: 32
      ipconfig0: 'ip=10.198.7.3/29,gw=10.198.3.1'
      ipconfig1: 'ip=10.198.8.3/29,gw=10.198.4.1'
      ipconfig2: 'ip=10.100.88.3/24'
      ipconfig3: 'ip=10.100.55.52/24'
      ipconfig4: 'ip=10.100.77.2/24'
      vlanconfig0: COREWAN1 
      vlanconfig1: COREWAN2 
      vlanconfig2: ISFW01 
      vlanconfig3: FTNTMGT 
      vlanconfig4: DMZ01 
      vlanconfig5: HAHUB01 

    - name: FGT-Hub-02a 
      vmid: 120
      cores: 1
      vcpus: 1
      memory: 4096
      type: FGT
      logsize: 32
      ipconfig0: 'ip=10.198.5.2/29,gw=10.198.5.1'
      ipconfig1: 'ip=10.198.6.2/29,gw=10.198.6.1'
      ipconfig2: 'ip=10.100.99.1/24'
      ipconfig3: 'ip=10.100.55.53/24'
      vlanconfig0: COREWAN3 
      vlanconfig1: COREWAN4 
      vlanconfig2: ISFW02 
      vlanconfig3: FTNTMGT 

    - name: FGT-Branch-01 
      vmid: 101
      cores: 1
      vcpus: 1
      memory: 4096
      type: FGT
      logsize: 32
      ipconfig0: 'ip=10.198.1.2/29,gw=10.198.1.1'
      ipconfig1: 'ip=10.198.2.2/29,gw=10.198.2.1'
      ipconfig2: 'ip=10.1.1.1/24'
      ipconfig3: 'ip=10.100.55.55/24'
      vlanconfig0: BRCHWAN1 
      vlanconfig1: BRCHWAN2 
      vlanconfig2: BRCHLAN1 
      vlanconfig3: FTNTMGT 

    - name: FGT-Branch-02 
      vmid: 102
      cores: 1
      vcpus: 1
      memory: 4096
      type: FGT
      logsize: 32
      ipconfig0: 'ip=10.198.3.2/29,gw=10.198.3.1'
      ipconfig1: 'ip=10.198.4.2/29,gw=10.198.4.1'
      ipconfig2: 'ip=10.1.2.1/24'
      ipconfig3: 'ip=10.100.55.56/24'
      vlanconfig0: BRCHWAN3 
      vlanconfig1: BRCHWAN4 
      vlanconfig2: BRCHLAN2 
      vlanconfig3: FTNTMGT 

    - name: FGT-Branch-03 
      vmid: 103
      cores: 1
      vcpus: 1
      memory: 4096
      type: FGT
      logsize: 32
      ipconfig0: 'ip=10.198.5.2/29,gw=10.198.5.1'
      ipconfig1: 'ip=10.198.6.2/29,gw=10.198.6.1'
      ipconfig2: 'ip=10.1.3.1/24'
      ipconfig3: 'ip=10.100.55.57/24'
      vlanconfig0: BRCHWAN5 
      vlanconfig1: BRCHWAN6 
      vlanconfig2: BRCHLAN3 
      vlanconfig3: FTNTMGT 

  fmg:
    - name: FMG 
      vmid: 201 
      cores: 4 
      vcpus: 4 
      memory: 16384 
      type: FMG
      logsize: 500 
      ipconfig0: 'ip=10.100.88.12/24,gw=10.100.88.1'
      ipconfig1: 'ip=10.100.55.12/24'
      ipconfig2: 'ip=172.16.3.12/24,gw=172.16.3.1'
      vlanconfig0: ISFW01 
      vlanconfig1: FTNTMGT 
      vlanconfig2: vmbr0 
      vlanconfig3: FTNTMGT 

  faz:
    - name: FAZ 
      vmid: 202 
      cores: 4 
      vcpus: 4 
      memory: 16384 
      type: FAZ
      logsize: 500
      ipconfig0: 'ip=10.100.88.2/24,gw=10.100.88.1'
      ipconfig1: 'ip=10.100.55.2/24'
      ipconfig2: 'ip=172.16.3.2/24,gw=172.16.3.1'
      vlanconfig0: ISFW01 
      vlanconfig1: FTNTMGT 
      vlanconfig2: vmbr0 
      vlanconfig3: FTNTMGT 

  ubuntu_oob:
    - name: Ubuntu-OOB
      ipconfig0: 'ip=172.16.3.80/24,gw=172.16.3.1'
      ipconfig1: 'ip=10.100.55.80/24'
      vlanconfig0: vmbr0
      vlanconfig1: FTNTMGT 
      vmid: 442

  ubuntu_tcgui:
    - name: Ubuntu-TCGUI
      ipconfig0:  'ip=172.16.3.90/24,gw=172.16.3.1'
      ipconfig1:  'ip=10.198.1.1/29'
      ipconfig2:  'ip=10.198.2.1/29'
      ipconfig3:  'ip=10.198.3.1/29'
      ipconfig4:  'ip=10.198.4.1/29'
      ipconfig5:  'ip=10.198.5.1/29'
      ipconfig6:  'ip=10.198.6.1/29'
      ipconfig7:  'ip=10.198.7.1/29'
      ipconfig8:  'ip=10.198.8.1/29'
      ipconfig9:  'ip=10.198.9.1/29'
      ipconfig10: 'ip=10.198.10.1/29'
      ipconfig11: 'ip=10.100.66.1/24'
      vlanconfig0:  vmbr0
      vlanconfig1:  BRCHWAN1 
      vlanconfig2:  BRCHWAN2 
      vlanconfig3:  BRCHWAN3 
      vlanconfig4:  BRCHWAN4 
      vlanconfig5:  BRCHWAN5 
      vlanconfig6:  BRCHWAN6 
      vlanconfig7:  COREWAN1 
      vlanconfig8:  COREWAN2 
      vlanconfig9:  COREWAN3 
      vlanconfig10: COREWAN4
      vlanconfig11: OFFNET 
      vmid: 443

  ubuntu_sdwan:
    - name: Ubuntu-00
      ipconfig0: 'ip=10.100.66.20/24,gw=10.100.66.1'
      ipconfig1: 'ip=10.100.55.70/24'
      vlanconfig0: OFFNET 
      vlanconfig1: FTNTMGT 
      vmid: 400

    - name: Ubuntu-01
      ipconfig0: 'ip=10.1.1.10/24,gw=10.1.1.1'
      ipconfig1: 'ip=10.100.55.71/24'
      vlanconfig0: BRCHLAN1 
      vlanconfig1: FTNTMGT 
      vmid: 401

    - name: Ubuntu-02
      ipconfig0: 'ip=10.1.2.10/24,gw=10.1.2.1'
      ipconfig1: 'ip=10.100.55.72/24'
      vlanconfig0: BRCHLAN2 
      vlanconfig1: FTNTMGT 
      vmid: 402

    - name: Ubuntu-03
      ipconfig0: 'ip=10.1.3.10/24,gw=10.1.3.1'
      ipconfig1: 'ip=10.100.55.73/24'
      vlanconfig0: BRCHLAN3 
      vlanconfig1: FTNTMGT 
      vmid: 403
      
    - name: Ubuntu-11
      ipconfig0: 'ip=10.100.88.100/24,gw=10.100.88.1'
      ipconfig1: 'ip=10.100.55.81/24'
      vlanconfig0: ISFW01 
      vlanconfig1: FTNTMGT 
      vmid: 411

    - name: Ubuntu-21
      ipconfig0: 'ip=10.100.99.100/24,gw=10.100.99.1'
      ipconfig1: 'ip=10.100.55.98/24'
      vlanconfig0: ISFW02 
      vlanconfig1: FTNTMGT 
      vmid: 421
      